ftp://anonymous:avallejos%40mcw.edu@grcf.jhmi.edu/OMIM/omim.txt.Z downing to /home/intermine/build/ratmine_src_data/tmp/omim.text.gz...
gzip -d -f  /home/intermine/build/ratmine_src_data/tmp/omim.text.gz 
perl -I/home/intermine/build/intermine_current/intermine/perl/lib omim-to-xml.pl --omim_text /home/intermine/build/ratmine_src_data/tmp/omim.text --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --omim_xml  
ftp://anonymous:avallejos%40mcw.edu@grcf.jhmi.edu/OMIM/genemap downing to /home/intermine/build/ratmine_src_data/tmp/genemap...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib omim-genemap-to-xml.pl --gene_map /home/intermine/build/ratmine_src_data/tmp/genemap --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --omim_xml  
ftp://rgd.mcw.edu/pub/data_release/GENES_RAT.txt downing to /home/intermine/build/ratmine_src_data/tmp/GENES_RAT.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-genes-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --rgd_genes /home/intermine/build/ratmine_src_data/tmp/GENES_RAT.txt --output_file ../../../ratmine_src_data/genome/genes/rgd_genes.xml   --taxon_id 10116 
ftp://rgd.mcw.edu/pub/data_release/GENES_HUMAN.txt downing to /home/intermine/build/ratmine_src_data/tmp/GENES_HUMAN.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-genes-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --rgd_genes /home/intermine/build/ratmine_src_data/tmp/GENES_HUMAN.txt --output_file ../../../ratmine_src_data/genome/genes/rgd_human_genes.xml   --taxon_id 9606 
ftp://rgd.mcw.edu/pub/data_release/GENES_MOUSE.txt downing to /home/intermine/build/ratmine_src_data/tmp/GENES_MOUSE.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-genes-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --rgd_genes /home/intermine/build/ratmine_src_data/tmp/GENES_MOUSE.txt --output_file ../../../ratmine_src_data/genome/genes/rgd_mouse_genes.xml   --taxon_id 10090 
ftp://rgd.mcw.edu/pub/data_release/RGD_ORTHOLOGS.txt downing to /home/intermine/build/ratmine_src_data/tmp/RGD_ORTHOLOGS.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-orthologs-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --input /home/intermine/build/ratmine_src_data/tmp/RGD_ORTHOLOGS.txt --output  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-gff3-sort.pl --dir /home/intermine/build/ratmine_src_data/tmp/Rat/Gene/ --out_dir ../../../ratmine_src_data/genome/gff/rat 
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-gff3-sort.pl --dir /home/intermine/build/ratmine_src_data/tmp/Rat/Sslp/ --out_dir ../../../ratmine_src_data/genome/gff/rat 
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-gff3-sort.pl --dir /home/intermine/build/ratmine_src_data/tmp/Rat/Qtl/ --out_dir ../../../ratmine_src_data/genome/gff/rat 
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-gff3-sort.pl --dir /home/intermine/build/ratmine_src_data/tmp/Mouse/Gene/ --out_dir  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-gff3-sort.pl --dir /home/intermine/build/ratmine_src_data/tmp/Human/Gene/ --out_dir  
ftp://rgd.mcw.edu/pub/data_release/QTLS_RAT.txt downing to /home/intermine/build/ratmine_src_data/tmp/QTLS_RAT.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-qtls-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --qtl_input /home/intermine/build/ratmine_src_data/tmp/QTLS_RAT.txt --xml_output  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib dbsnp-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --input /home/intermine/build/ratmine_src_data/dbSNP/ --output  --taxon 10116 --assembly RGSC_v3.4 --download 
perl -I/home/intermine/build/intermine_current/intermine/perl/lib get_and_split_uniprot.pl --taxon 10116 --output_dir  
http://www.geneontology.org/ontology/obo_format_1_2/gene_ontology.1_2.obo downing to ...
http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/gene-associations/gene_association.rgd.gz?rev=HEAD downing to /home/intermine/build/ratmine_src_data/tmp/gene_association.rgd.gz...
gzip -d -f  /home/intermine/build/ratmine_src_data/tmp/gene_association.rgd.gz 
sort -k 2,2  /home/intermine/build/ratmine_src_data/tmp/gene_association.rgd  >  /home/intermine/build/ratmine_src_data/go-annotation/gene_association.rgd 
ftp://ftp.informatics.jax.org/pub/reports/MPheno_OBO.ontology downing to /home/intermine/build/ratmine_src_data/mp/MPheno_OBO.obo...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/rattus_genes_mp downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/mus_genes_mp downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/homo_genes_mp downing to ...
ftp://rgd.mcw.edu/pub/ontology/pathway/pathway.obo downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/rattus_genes_pw downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/mus_genes_pw downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/homo_genes_pw downing to ...
ftp://rgd.mcw.edu/pub/ontology/disease/CTD.obo downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/rattus_genes_do downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/mus_genes_do downing to ...
ftp://rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/homo_genes_do downing to ...
http://rest.bioontology.org/bioportal/ontologies/download/42515 downing to /home/intermine/build/ratmine_src_data/rs/strainont03_24_10_v2.0.obo...
ftp://rgd.mcw.edu/pub/data_release/STRAINS.txt downing to /home/intermine/build/ratmine_src_data/tmp/strains.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-strains-to-xml.pl --rgd_strains /home/intermine/build/ratmine_src_data/tmp/strains.txt --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --output_file  --strain_obo /home/intermine/build/ratmine_src_data/rs/strainont03_24_10_v2.0.obo 
ftp://rgd.mcw.edu/pub/data_release/SSLPS_RAT.txt downing to /home/intermine/build/ratmine_src_data/tmp/sslp_rat.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-sslp-to-xml.pl --input /home/intermine/build/ratmine_src_data/tmp/sslp_rat.txt --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --output  
ftp://rgd.mcw.edu/pub/data_release/SSLPS_ALLELES_RAT.txt downing to /home/intermine/build/ratmine_src_data/tmp/sslp_alleles_rat.txt...
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rgd-sslp-alleles-to-xml.pl --input /home/intermine/build/ratmine_src_data/tmp/sslp_alleles_rat.txt --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --output  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib geo-platform-to-xml.pl --input /home/intermine/build/geostuff/geoannotations/ --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --output  --download  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rat-geo-soft-to-xml.pl --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --input /home/intermine/build/geostuff/geoplatforms --output  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rat-geo-soft-to-xml.pl --series  --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --input /home/intermine/build/geostuff/geoseries --output  
perl -I/home/intermine/build/intermine_current/intermine/perl/lib rat-geo-soft-to-xml.pl --samples  --model /home/intermine/build/intermine_current/ratmine/dbmodel/build/model/genomic_model.xml --input /home/intermine/build/geostuff/geoseries --output  
